# Generated by Django 4.2.1 on 2023-07-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aws_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=64)),
                ('image_ID', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='aws_intance_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='aws_security_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_group_name', models.CharField(max_length=64)),
                ('security_group_id', models.CharField(max_length=64)),
            ],
        ),
    ]
