# Generated by Django 4.2.1 on 2023-07-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aws_intance_type',
            new_name='aws_instance_type',
        ),
    ]
