# Generated by Django 4.2.1 on 2023-07-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0002_rename_aws_intance_type_aws_instance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='aws_keyname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.CharField(max_length=64)),
            ],
        ),
    ]
