# Generated by Django 4.2.1 on 2023-08-04 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0003_aws_keyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='aws_instance_type',
            name='cpu',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aws_instance_type',
            name='ram',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='aws_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=64, unique=True)),
                ('project_name', models.CharField(max_length=64)),
                ('created_by', models.CharField(max_length=64)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('region', models.CharField(max_length=64)),
                ('status', models.CharField(default='running', max_length=64)),
                ('instance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws_app.aws_instance_type')),
            ],
        ),
    ]
