# Generated by Django 4.2.1 on 2023-08-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0004_aws_instance_type_cpu_aws_instance_type_ram_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aws_security_group',
        ),
    ]
