# Generated by Django 4.2.1 on 2023-08-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0005_delete_aws_security_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aws_instance',
            old_name='project_name',
            new_name='instance_id',
        ),
    ]
