# Generated by Django 4.2.1 on 2023-08-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0006_rename_project_name_aws_instance_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws_instance',
            name='status',
            field=models.CharField(default='Running', max_length=64),
        ),
    ]
