# Generated by Django 4.2.1 on 2023-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0007_alter_aws_instance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws_instance_type',
            name='ram',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
