# Generated by Django 4.2.1 on 2023-08-16 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0011_alter_billing_snap_index_created'),
        ('aws_app', '0008_alter_aws_instance_type_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='snap_aws_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=64, unique=True)),
                ('instance_id', models.CharField(max_length=64)),
                ('created_by', models.CharField(max_length=64)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('region', models.CharField(max_length=64)),
                ('status', models.CharField(default='Running', max_length=64)),
                ('aws_snap_index_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billow.billing_snap_index')),
                ('instance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws_app.aws_instance_type')),
            ],
        ),
    ]
