# Generated by Django 4.2.1 on 2023-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0009_snap_aws_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snap_aws_instance',
            name='instance_name',
            field=models.CharField(max_length=64),
        ),
    ]
