# Generated by Django 4.2.1 on 2023-05-24 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Snap_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('hash_key', models.CharField(default=None, max_length=64)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cloud_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=128)),
                ('secret_token', models.CharField(max_length=128)),
                ('client_id', models.CharField(max_length=128)),
                ('subscription_id', models.CharField(max_length=256)),
                ('project_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cloud_Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(max_length=64, unique=True)),
                ('auth_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('program_poc_obj', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Program Point Of Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('program_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billow.program')),
            ],
        ),
        migrations.CreateModel(
            name='Cloud_Account_Team_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billow.cloud_account')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billow.team')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('billing_snap_index_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billow.billing_snap_index')),
                ('cloud_account_team_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billow.cloud_account_team_name')),
            ],
        ),
    ]
