# Generated by Django 4.2.1 on 2023-06-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0002_cloud_account_active_cloud_account_cloud_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud_account',
            name='cloud_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cloud_account',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloud_account',
            name='client_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cloud_account',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cloud_account',
            name='project_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cloud_account',
            name='secret_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cloud_account',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cloud_account',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cloud_account',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
