# Generated by Django 4.2.1 on 2023-06-07 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billow', '0002_cloud_account_active_cloud_account_cloud_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, null=True)),
                ('program_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billow.program')),
                ('team_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billow.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
