# Generated by Django 4.2.1 on 2023-06-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0003_cloud_account_cloud_name_alter_cloud_account_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud_account',
            name='secret_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
