# Generated by Django 4.2.1 on 2023-06-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
