# Generated by Django 4.2.1 on 2023-06-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0004_alter_cloud_account_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud_account',
            name='secret_token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
