# Generated by Django 4.2.1 on 2023-07-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0004_delete_userprofile'),
        ('billow', '0007_alter_cloud_account_secret_token'),
    ]

    operations = [
    ]
