# Generated by Django 4.2.1 on 2023-07-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0008_merge_20230703_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='cloud_account_team_name',
        ),
        migrations.AddField(
            model_name='billing',
            name='cloud_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billow.cloud_account'),
            preserve_default=False,
        ),
    ]
