# Generated by Django 4.2.1 on 2023-07-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0009_remove_billing_cloud_account_team_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='total_cost',
        ),
    ]
