# Generated by Django 4.2.1 on 2023-08-21 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0011_alter_billing_snap_index_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance_Snap_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('hash_key', models.CharField(default=None, max_length=64)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
