# Generated by Django 4.2.1 on 2023-08-03 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('gcp_app', '0001_initial'), ('gcp_app', '0002_gcp_instance'), ('gcp_app', '0003_gcp_instance_instance_name_gcp_instance_machine_type_and_more'), ('gcp_app', '0004_alter_gcp_instance_machine_type_and_more'), ('gcp_app', '0005_alter_gcp_instance_machine_type_and_more'), ('gcp_app', '0006_remove_gcp_instance_network_link_cpu_series_cpu_and_more'), ('gcp_app', '0007_alter_cpu_series_cpu'), ('gcp_app', '0008_alter_cpu_series_cpu'), ('gcp_app', '0009_alter_gcp_instance_machine_type_and_more'), ('gcp_app', '0010_alter_gcp_instance_status'), ('gcp_app', '0011_alter_gcp_instance_created_by')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=64)),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Gcp_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcp_app.zone')),
                ('instance_name', models.CharField(default=False, max_length=64)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcp_app.cpu_series')),
                ('project', models.CharField(default=False, max_length=64)),
                ('created_by', models.CharField(default='admin', max_length=128)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Running', max_length=64)),
            ],
        ),
    ]
