# Generated by Django 4.2.1 on 2023-08-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gcp_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_link', models.CharField(max_length=64)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcp_app.zone')),
            ],
        ),
    ]
