# Generated by Django 4.2.1 on 2023-08-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcp_app', '0002_gcp_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcp_instance',
            name='instance_name',
            field=models.CharField(default=False, max_length=64),
        ),
        migrations.AddField(
            model_name='gcp_instance',
            name='machine_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gcp_app.cpu_series'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcp_instance',
            name='project',
            field=models.CharField(default=False, max_length=64),
        ),
    ]
