# Generated by Django 4.2.1 on 2023-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp_app', '0004_alter_gcp_instance_machine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcp_instance',
            name='machine_type',
            field=models.CharField(default=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='gcp_instance',
            name='network_link',
            field=models.CharField(max_length=128),
        ),
    ]
