# Generated by Django 4.2.1 on 2023-08-03 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gcp_app', '0005_alter_gcp_instance_machine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcp_instance',
            name='network_link',
        ),
        migrations.AddField(
            model_name='cpu_series',
            name='cpu',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpu_series',
            name='ram',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcp_instance',
            name='created_by',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcp_instance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gcp_instance',
            name='status',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
