# Generated by Django 4.2.1 on 2023-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp_app', '0006_remove_gcp_instance_network_link_cpu_series_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_series',
            name='cpu',
            field=models.FloatField(),
        ),
    ]
