# Generated by Django 4.2.1 on 2023-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp_app', '0007_alter_cpu_series_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_series',
            name='cpu',
            field=models.IntegerField(),
        ),
    ]
