# Generated by Django 4.2.1 on 2023-08-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcp_app', '0008_alter_cpu_series_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcp_instance',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcp_app.cpu_series'),
        ),
        migrations.AlterField(
            model_name='gcp_instance',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcp_app.zone'),
        ),
    ]
