# Generated by Django 4.2.1 on 2023-08-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp_app', '0009_alter_gcp_instance_machine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcp_instance',
            name='status',
            field=models.CharField(default='Running', max_length=64),
        ),
    ]
