# Generated by Django 4.2.1 on 2023-08-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gcp_app', '0012_alter_cpu_series_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcp_instance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
