# Generated by Django 4.2.1 on 2023-08-16 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0011_alter_billing_snap_index_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gcp_app', '0013_alter_gcp_instance_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='snap_gcp_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default=False, max_length=64)),
                ('instance_name', models.CharField(default=False, max_length=64)),
                ('status', models.CharField(default='Running', max_length=64)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gcp_snap_index_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billow.billing_snap_index')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcp_app.cpu_series')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcp_app.zone')),
            ],
        ),
    ]
