# Generated by Django 4.2.1 on 2023-08-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azure_instance',
            name='os_disk_name',
        ),
    ]
