# Generated by Django 4.2.1 on 2023-08-16 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billow', '0011_alter_billing_snap_index_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('azure_app', '0003_rename_disk_name_azure_instance_os_disk_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azure_instance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='snap_azure_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=64)),
                ('network_interface_name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('resource_group_name', models.CharField(max_length=64)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('azure_snap_index_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billow.billing_snap_index')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('harware_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_app.hardware_profile')),
                ('image_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_app.image')),
                ('os_disk_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_app.os_disk')),
            ],
        ),
    ]
